version: "3.5"
services:
  metabase:
    container_name: metabase-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: test
      MB_DB_HOST: docker.for.mac.localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s