version: "3.5"
services:
  mysql:
    container_name: mysql-test
    image: mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
      
  postgres:
    container_name: postgres-test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432